### ISSUE TITLE
SOFTEAM Partner

### ISSUE THREAD

**Issue by alebagnato** [openETCS/ITEA3-follow-up#19]
SOFTEAM is a private software vendor and engineering company with about 910 employees and about €82 M in revenues. SOFTEAM headquarters are based in Paris. The main subsidiaries are in Saint-Quentin-en-Yvelines, Toulouse, Rennes, Nantes and Sophia Antipolis.
SOFTEAM develops four main activities: 
(1)	CASE tool editing with “Modelio” UML Editor and Tool set, which has been on the mar-ket since 1992; 
(2)	e-Citiz - a platform for Business Process Management for both e-government and com-panies, and which has been on the market since 2004.
(3)	Consulting: As a provider of object-oriented methodology, and as an active OMG con-tributor; 
(4)	Training: SOFTEAM provides training in related technical areas (languages, techniques, tools) and in methodological areas; 
SOFTEAM solutions and services are used in many industrial domains including: aerospace & defence, energy, automobile, telecommunications, banking & insurance, government.

RELEVANCE OF PARTNER ACTIVITIES TO THE PROJECT
As a contributing member and voter since 1994, SOFTEAM is deeply involved in the work of the OMG and, in particular, the standardisation of UML. SOFTEAM, represented by the VP of R&D, Philippe DESFRAY, maintains a close synergy between the significant R&D efforts and its involvement within the OMG. SOFTEAM directed or was involved in establishing of number of specification including: UML2 profiles, SPEM, U2TP and SoaML.
In order to secure its leading position in cutting edge technologies for more than 15 years, SOFTEAM’s R&D De-partment actively participates in various national and EU research projects in the software engineering and modelling domains. 

SOFTEAM will bring its professional tools for modelling, code generation and code reverse engineering.
Modelio (www.modelio.org) - Modelio is an open source modelling environment (UML2, BPMN2, MARTE, SysML, and other profiles/standards). Modelio delivers a broad-focused range of standards-based functionali-ties for software developers, analysts, designers, business architects and system architects.
•	Modelio UML environment (Modelio.org), SOFTEAM’s open source systems engineering modelling envi-ronment (http://www.modelio.org

<to be completed>

**Comment by KlausRuedigerHase** [comment]
Sounds pretty good and seems to fit quite well in our scope of work. Creating and verifying our formalized model approach for the interfaces between train/vehicle control level and ETCS OBU on the one hand and refactoring/completing/upgrading the EVC ETCS software for SRS 3.5.  Question: Has your organization ever used SCADE from ANSYS (former Esterel, France)?  I looked into the Modelio website and I am wondering why this was not considered during our tools review process in the openETCS@ITEA2 project ?! (Possible reason: SOFTEAM was not with us back then, why?)

**Comment by alebagnato** [comment]
Hi Klaus,
yes we could cover the part at http://www.esterel-technologies.com/products/scade-system/
and as you may have seen already from the modelio.org web site (http://forge.modelio.org/projects) we have very advanced profiles for OMG SySML and MARTE. Softeam is platform member at Object Management Group and member of the UML, SysML and MARTE Standardization task forces.
We are very happy to be in the openETCS/ITEA3-follow-up now :)

**Comment by AndreySadovykh** [comment]
Could you please invite andrey.sadovykh@softeam.fr and alessandra.bagnato@softeam.fr to the Itea.org project idea site?

Thanks,

**Comment by alebagnato** [comment]
Hi Klaus,
I seem not to have received the invitation yet ..
I have only got the invitation to join the "
ITEA project idea invitation: 13: PORVI" 
and I cannot see our project in my ITEA 3 projects list ..
