### ISSUE TITLE
2.2.3. Impact on quality of life

### ISSUE THREAD

**Issue by KlausRuedigerHase** [openETCS/ITEA3-follow-up#28]

**Comment by AndreySadovykh** [comment]
My notes on the paragraph:
Stats for introduction
Safer since:
more affordable (cost), wider availability, more safer railway systems.
more interoperable. reference design
open source, means cross validation and rapide debugging.

I'm putting that to few para

**Comment by AndreySadovykh** [comment]
Added text to [section](https://github.com/openETCS/ITEA3-follow-up/wiki/2.2.3.-Impact-on-quality-of-life)

**Comment by HolgerBlasumSYSGO** [comment]
Added short intro on technical debt I promised during telco.
